spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: ${dburl} #4칸
    username: ${dbusername}
    password: ${dbpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      #ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        default_batch_fetch_size: 10
        #show_sql: true #띄어쓰기 8칸

        format_sql: true #띄어쓰기 8칸

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  #org.hibernate.type: trace #띄어쓰기 2칸